"""CNBV XBRL - as-filed financials for Mexican (BMV) issuers.

The commercial providers have no BMV fundamentals: FMP answers HTTP 402 for
non-US listings even on the NYSE-listed ADRs, and Fiscal.ai cannot resolve the
symbols. This is the only route to statements for Mexican names, and it is the
as-filed ground truth - the CNBV is the regulator these companies file with.

There is no documented API. The portal at xbrl.cnbv.gob.mx is an AngularJS app
whose backend was worked out by watching what it calls:

    POST /DocumentoInstancia/ConsultarEnviosInformacionDataTable
        DataTables server-side protocol, plus a `clavePizarra` filter.
        Note the standard `search[value]` parameter is NOT supported - sending
        a non-empty one makes the endpoint return a bare `null`.

    POST /DocumentoInstancia/BajarArchivoDocumentoInstancia
        {idDocIns, tipoArchivo: 4} -> the filing as pre-parsed JSON, gzipped.
        This is the viewer's own model, so the XBRL is already resolved into
        facts, contexts and units; no XBRL parser is needed.

Neither endpoint requires a key, a cookie or a session.
"""
from __future__ import annotations

import functools
import ssl
import threading
from datetime import date
from pathlib import Path
from typing import Any

import certifi
import httpx

import quota
from sources import (
    FUNDAMENTALS, SourceError, fundamental_row, has_exchange_suffix, to_date, to_float,
)

NAME = "cnbv"
CAPABILITIES = {FUNDAMENTALS}
BASE_URL = "https://xbrl.cnbv.gob.mx"
LIST_PATH = "/DocumentoInstancia/ConsultarEnviosInformacionDataTable"
FILE_PATH = "/DocumentoInstancia/BajarArchivoDocumentoInstancia"

# The portal rejects a default python-httpx agent.
USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) TisellTerminal/1.0"

# xbrl.cnbv.gob.mx serves its leaf certificate without the GlobalSign
# intermediate that signs it, so OpenSSL cannot build a chain ("unable to get
# local issuer certificate"). curl and browsers paper over this by fetching the
# missing certificate from the leaf's AIA extension; Python does not.
#
# The fix is to supply the intermediate rather than to stop verifying: the
# certificate below is the public GlobalSign RSA OV SSL CA 2018, added on top
# of certifi's roots. Verification stays fully enabled. It expires 2028-11-21;
# refresh it from the AIA URL in the leaf if this ever starts failing.
CERT_DIR = Path(__file__).resolve().parent.parent / "certs"
INTERMEDIATE = CERT_DIR / "globalsign-rsa-ov-ssl-ca-2018.pem"


@functools.lru_cache(maxsize=1)
def _ssl_context() -> ssl.SSLContext:
    context = ssl.create_default_context(cafile=certifi.where())
    if INTERMEDIATE.exists():
        context.load_verify_locations(str(INTERMEDIATE))
    return context
LIST_COLUMNS = 13
FILE_TYPE_PARSED_JSON = 4

# CNBV presentation roles are prefixed with a stable code. The five that make
# up the primary statements are mapped onto the same names the US providers
# use, so a statement tab means the same thing whichever source filled it.
ROLE_STATEMENTS = {
    "[210000]": "balance",
    "[310000]": "income",
    "[410000]": "comprehensive_income",
    "[520000]": "cash_flow",
    "[610000]": "equity_changes",
}
NOTES_STATEMENT = "notes"

# A filing reports the same concept over several durations that all END on the
# same date: the quarter itself, year-to-date, and trailing twelve months. Key
# on the end date alone and they collapse into one another, so a "quarterly"
# revenue can silently be a TTM figure. Duration is therefore part of the
# selection, not an afterthought.
TARGET_MONTHS = {"quarterly": 3, "annual": 12}
MONTH_TOLERANCE = 1

# Only the financial-statement taxonomies. "Eventos Relevantes" filings are
# press releases with no figures, and they are the bulk of the 68k documents.
FINANCIAL_TAXONOMY_HINTS = ("IFRS", "NIIF")
NON_FINANCIAL_HINTS = ("Eventos Relevantes", "Sostenibilidad", "SDS")

# Yahoo appends the share series to the BMV ticker; CNBV files under the bare
# clave de pizarra. There is no rule that recovers one from the other
# (LACOMERUBC -> LACOMER, GCARSOA1 -> GCARSO), so candidates are generated by
# stripping known series suffixes longest-first and confirmed against the API.
SERIES_SUFFIXES = (
    "UBC", "UBD", "CPO", "A1", "B-1", "C-1", "B1", "13", "14", "11", "12",
    "O", "B", "A", "L", "1", "2",
)

_clave_cache: dict[str, str] = {}
_cache_lock = threading.Lock()


def is_configured() -> bool:
    return True  # no credentials of any kind


def supports(ticker: str) -> bool:
    """The mirror image of the US-only providers: BMV listings only."""
    return has_exchange_suffix(ticker) and ticker.strip().upper().endswith(".MX")


def _post(path: str, data: dict[str, Any] | str, timeout: float = 240.0) -> httpx.Response:
    quota.record(NAME)
    try:
        return httpx.post(
            f"{BASE_URL}{path}", content=data if isinstance(data, str) else None,
            data=None if isinstance(data, str) else data,
            headers={
                "User-Agent": USER_AGENT,
                "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                "Accept-Encoding": "gzip, deflate",
                "X-Requested-With": "XMLHttpRequest",
                "Referer": f"{BASE_URL}/visorXbrl.html",
            },
            timeout=timeout, follow_redirects=True, verify=_ssl_context(),
        )
    except httpx.HTTPError as exc:
        raise SourceError(f"cnbv: request failed: {exc}") from exc


def _datatables_body(clave: str, start: int = 0, length: int = 50) -> dict[str, Any]:
    body: dict[str, Any] = {
        "draw": 1, "start": start, "length": length,
        # Must stay empty: a non-empty global search makes the endpoint
        # return a bare `null` instead of results.
        "search[value]": "", "search[regex]": "false",
        "order[0][column]": 0, "order[0][dir]": "desc",
        "clavePizarra": clave,
    }
    for index in range(LIST_COLUMNS):
        body[f"columns[{index}][data]"] = index
        body[f"columns[{index}][name]"] = ""
        body[f"columns[{index}][searchable]"] = "true"
        body[f"columns[{index}][orderable]"] = "true"
        body[f"columns[{index}][search][value]"] = ""
        body[f"columns[{index}][search][regex]"] = "false"
    return body


def list_filings(clave: str, length: int = 50) -> list[dict[str, Any]]:
    """Filings for one clave de pizarra, newest first."""
    response = _post(LIST_PATH, _datatables_body(clave, length=length))
    if response.status_code >= 400:
        raise SourceError(f"cnbv: HTTP {response.status_code} listing {clave}")
    try:
        payload = response.json()
    except ValueError as exc:
        raise SourceError(f"cnbv: non-JSON listing for {clave}") from exc
    if not payload or not isinstance(payload, dict):
        raise SourceError(f"cnbv: empty listing for {clave}")

    filings = []
    for row in payload.get("data") or []:
        if len(row) < 12:
            continue
        filings.append({
            "id": row[0], "sent_at": row[2], "clave": (row[3] or "").strip().upper(),
            "periodo": row[4], "taxonomia": row[5], "archivo": row[6],
            "ejercicio": row[8], "trimestre": row[9], "period_end": to_date(row[11]),
        })
    return filings


def candidate_claves(ticker: str) -> list[str]:
    base = ticker.strip().upper().removesuffix(".MX")
    seen, out = set(), []
    for candidate in [base] + [
        base.removesuffix(suffix) for suffix in SERIES_SUFFIXES if base.endswith(suffix)
    ]:
        candidate = candidate.rstrip("-")
        if candidate and candidate not in seen:
            seen.add(candidate)
            out.append(candidate)
    return out


def resolve_clave(ticker: str) -> str:
    """Map a Yahoo BMV symbol to the clave de pizarra CNBV files under."""
    symbol = ticker.strip().upper()
    with _cache_lock:
        if symbol in _clave_cache:
            return _clave_cache[symbol]

    for candidate in candidate_claves(symbol):
        try:
            filings = list_filings(candidate, length=25)
        except SourceError:
            continue
        # clavePizarra matches as a prefix, so require an exact hit.
        if any(f["clave"] == candidate for f in filings):
            with _cache_lock:
                _clave_cache[symbol] = candidate
            return candidate

    raise SourceError(f"cnbv: no clave de pizarra matched {symbol}")


def _is_financial(taxonomia: str) -> bool:
    text = taxonomia or ""
    if any(hint.lower() in text.lower() for hint in NON_FINANCIAL_HINTS):
        return False
    return any(hint.lower() in text.lower() for hint in FINANCIAL_TAXONOMY_HINTS)


def fetch_document(filing_id: str) -> dict[str, Any]:
    """The filing as the viewer's own pre-parsed JSON model."""
    response = _post(FILE_PATH, {"idDocIns": filing_id,
                                 "tipoArchivo": FILE_TYPE_PARSED_JSON})
    if response.status_code >= 400:
        raise SourceError(f"cnbv: HTTP {response.status_code} downloading {filing_id}")
    try:
        return response.json()
    except ValueError as exc:
        raise SourceError(f"cnbv: filing {filing_id} was not JSON") from exc


def _walk_presentation(node: dict[str, Any], order: list[str]) -> None:
    """Depth-first over the presentation tree, which is the filer's own order."""
    concept = node.get("IdConcepto")
    if concept:
        order.append(concept)
    for child in node.get("SubEstructuras") or []:
        _walk_presentation(child, order)


def presentation_index(document: dict[str, Any]) -> dict[str, tuple[str, int]]:
    """Map concept -> (statement, position) from the filing's own taxonomy.

    A financial statement reads top to bottom - Revenue, Cost of Sales, Gross
    Profit - and that order is part of the filing, not something to invent.
    The first role a concept appears in wins, so a line shown on the balance
    sheet is not relabelled by a later note that also references it.
    """
    index: dict[str, tuple[str, int]] = {}
    for role in (document.get("Taxonomia") or {}).get("RolesPresentacion") or []:
        name = role.get("Nombre") or ""
        code = name.split(" ", 1)[0]
        statement = ROLE_STATEMENTS.get(code, NOTES_STATEMENT)
        order: list[str] = []
        for structure in role.get("Estructuras") or []:
            _walk_presentation(structure, order)
        for position, concept in enumerate(order):
            index.setdefault(concept, (statement, position))
    return index


def _span_months(start: date | None, end: date | None) -> int | None:
    """Inclusive month span of a duration context."""
    if start is None or end is None:
        return None
    return (end.year - start.year) * 12 + (end.month - start.month) + 1


def _currency(document: dict[str, Any], unit_id: str | None) -> str | None:
    unit = (document.get("UnidadesPorId") or {}).get(unit_id or "")
    if not unit:
        return None
    measures = unit.get("Medidas") or unit.get("MedidasNumerador") or []
    for measure in measures:
        name = measure.get("Nombre")
        # ISO-4217 currency codes only; "shares" and "pure" are not currencies.
        if name and len(name) == 3 and name.isalpha():
            return name.upper()
    return None


def extract_facts(document: dict[str, Any], ticker: str,
                  period_type: str) -> list[dict[str, Any]]:
    """Flatten the document's facts into the data layer's long rows.

    Only non-dimensional facts are kept. Dimensional ones are breakdowns by
    segment, equity component or business line; mixing them with the headline
    figures would double-count every total.
    """
    facts = document.get("HechosPorId") or {}
    contexts = document.get("ContextosPorId") or {}
    layout = presentation_index(document)
    target_months = TARGET_MONTHS.get(period_type, 3)

    rows: list[dict[str, Any]] = []
    for fact in facts.values():
        if not fact.get("EsNumerico") or fact.get("EsValorNil"):
            continue
        value = to_float(fact.get("ValorNumerico"))
        if value is None:
            continue

        context = contexts.get(fact.get("IdContexto") or "")
        if not context or context.get("ContieneInformacionDimensional"):
            continue

        period = context.get("Periodo") or {}
        is_duration = period.get("Tipo") == 2
        # Tipo 1 = instant (balance sheet), 2 = duration (income, cash flow).
        raw_end = period.get("FechaFin") if is_duration else period.get("FechaInstante")
        period_end = to_date(raw_end)
        if period_end is None or period_end.year < 1990:
            continue

        if is_duration:
            # Keep only the duration the caller asked for. An instant has no
            # duration to disambiguate, so balance-sheet items pass straight
            # through.
            span = _span_months(to_date(period.get("FechaInicio")), period_end)
            if span is None or abs(span - target_months) > MONTH_TOLERANCE:
                continue

        concept = fact.get("IdConcepto")
        if not concept:
            continue

        statement, ordinal = layout.get(concept, (NOTES_STATEMENT, None))
        rows.append(fundamental_row(
            ticker, period_end, period_type, statement, concept, value,
            _currency(document, fact.get("IdUnidad")), ordinal,
        ))
    return rows


def fetch_fundamentals(ticker: str, period_type: str = "annual",
                       limit: int = 8) -> list[dict[str, Any]]:
    """As-filed statements for a BMV issuer.

    CNBV filings are quarterly. Q4 carries the full-year cumulative figures, so
    those are what an "annual" request returns.
    """
    if not supports(ticker):
        raise SourceError(f"cnbv: {ticker} is not a BMV listing")

    clave = resolve_clave(ticker)
    filings = [f for f in list_filings(clave, length=60)
               if f["clave"] == clave and _is_financial(f["taxonomia"])]
    if not filings:
        raise SourceError(f"cnbv: no financial-statement filings for {clave}")

    if period_type == "annual":
        wanted = [f for f in filings if str(f["trimestre"]).strip() in ("4", "")]
    else:
        wanted = filings

    # Newest first, then keep `limit` distinct period ends.
    wanted.sort(key=lambda f: f["period_end"] or date.min, reverse=True)
    chosen, seen_periods = [], set()
    for filing in wanted:
        if filing["period_end"] in seen_periods:
            continue
        seen_periods.add(filing["period_end"])
        chosen.append(filing)
        if len(chosen) >= limit:
            break

    if not chosen:
        raise SourceError(
            f"cnbv: no {period_type} filings for {clave} "
            f"({len(filings)} financial filings seen)"
        )

    # One value per (concept, period). A concept can repeat within a document
    # across equivalent contexts, and a later filing restates earlier periods -
    # `chosen` is newest-first, so the first value seen is the current one.
    best: dict[tuple[str, date], dict[str, Any]] = {}
    problems: list[str] = []
    for filing in chosen:
        try:
            document = fetch_document(filing["id"])
        except SourceError as exc:
            problems.append(str(exc))
            continue
        for row in extract_facts(document, ticker, period_type):
            best.setdefault((row["metric"], row["period_end"]), row)

    rows = list(best.values())
    if not rows:
        raise SourceError(
            f"cnbv: no usable facts for {clave}" +
            (f" ({'; '.join(problems[:2])})" if problems else "")
        )
    return rows
